"""Add partial marking flag to Test model

Revision ID: 02a2b9df2ab8
Revises: b367cbc49fdf
Create Date: 2025-12-17 11:14:13.624488

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '02a2b9df2ab8'
down_revision = 'b367cbc49fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('partial_marks', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'partial_marks')
    # ### end Alembic commands ###
