"""Add omr Field to Test Model

Revision ID: 145b493d175b
Revises: b367cbc49fdf
Create Date: 2025-12-10 11:10:21.910125

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '145b493d175b'
down_revision = 'b367cbc49fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('omr', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'omr')
    # ### end Alembic commands ###
