"""add bookmarked field to candidate_test_answer model

Revision ID: 176a93f83db9
Revises: ae688477032d
Create Date: 2026-01-10 06:09:50.216551

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '176a93f83db9'
down_revision = 'ae688477032d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_test_answer', sa.Column('bookmarked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_test_answer', 'bookmarked')
    # ### end Alembic commands ###
