"""Add omr Field to Test Model

Revision ID: 1d236ebb6a4b
Revises: f915b1a8ea67
Create Date: 2026-01-09 12:44:05.880075

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1d236ebb6a4b'
down_revision = 'f915b1a8ea67'
branch_labels = None
depends_on = None

omrmode = sa.Enum('NEVER', 'ALWAYS', 'OPTIONAL', name='omrmode')
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    omrmode.create(op.get_bind())
    op.add_column('test', sa.Column('omr', sa.Enum('NEVER', 'ALWAYS', 'OPTIONAL', name='omrmode'), server_default='NEVER', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'omr')
    omrmode.drop(op.get_bind())
    # ### end Alembic commands ###
