"""Add language field to Test model

Revision ID: 21a569847360
Revises: b367cbc49fdf
Create Date: 2025-12-02 14:27:02.917431

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21a569847360'
down_revision = 'b367cbc49fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    language_enum = sa.Enum('EN_US', 'HI_IN', 'MR_IN', name='languagelabels')
    language_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('test', sa.Column('language', language_enum, server_default='EN_US', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'language')
    sa.Enum(name='languagelabels').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
