"""Adding Optimized Locale Field to Test Model

Revision ID: 2457a2835629
Revises: 61e8fcf99159
Create Date: 2026-01-02 15:09:47.755401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2457a2835629'
down_revision = '61e8fcf99159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'locale',
               existing_type=postgresql.ENUM('EN_US', 'HI_IN', name='localeenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'EN_US'::localeenum"))

        # 2) Convert stored values to BCP-47 tags
    op.execute(
        """
        UPDATE test
        SET locale = CASE locale
            WHEN 'EN_US' THEN 'en-US'
            WHEN 'HI_IN' THEN 'hi-IN'
            ELSE locale
        END
        """
    )

    op.alter_column(
        "test",
        "locale",
        server_default=sa.text("'en-US'"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'locale',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('EN_US', 'HI_IN', name='localeenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'EN_US'::localeenum"))

    op.execute(
        """
        UPDATE test
        SET locale = CASE locale
            WHEN 'en-US' THEN 'EN_US'
            WHEN 'hi-IN' THEN 'HI_IN'
            ELSE locale
        END
        """
    )
    # ### end Alembic commands ###
