"""Adding Optimized Locale Field to Test Model

Revision ID: 2457a2835629
Revises: 61e8fcf99159
Create Date: 2026-01-02 15:09:47.755401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2457a2835629'
down_revision = '61e8fcf99159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'locale',
               existing_type=postgresql.ENUM('EN_US', 'HI_IN', name='localeenum'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'EN_US'::localeenum"))

        # 2) Convert stored values to BCP-47 tags
    op.execute(
        """
       UPDATE test SET locale='en-US';
        """
    )

    op.alter_column(
        "test",
        "locale",
        server_default=sa.text("'en-US'"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     # 1. Ensure data matches enum labels
    op.execute("""
        UPDATE test SET locale='EN_US' WHERE locale='en-US';
    """)

    # 2. Drop string-based default
    op.execute("""
        ALTER TABLE test
        ALTER COLUMN locale DROP DEFAULT
    """)

    # 3. Convert VARCHAR -> ENUM explicitly
    op.execute("""
        ALTER TABLE test
        ALTER COLUMN locale
        TYPE localeenum
        USING locale::localeenum
    """)

    # 4. Restore enum-based default
    op.execute("""
        ALTER TABLE test
        ALTER COLUMN locale
        SET DEFAULT 'EN_US'
    """)

    # ### end Alembic commands ###
