"""add subjective_answer_min_length to question_revision

Revision ID: 26a60da52cb1
Revises: 951c45c3eba3
Create Date: 2026-04-28 16:40:59.182312

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '26a60da52cb1'
down_revision = '951c45c3eba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_revision', sa.Column('subjective_answer_min_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_revision', 'subjective_answer_min_length')
    # ### end Alembic commands ###
