"""Add language field to Test model

Revision ID: 2b22be39816d
Revises: b367cbc49fdf
Create Date: 2025-11-27 14:51:16.128393

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2b22be39816d'
down_revision = 'b367cbc49fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'language')
    # ### end Alembic commands ###
