"""Add new feedback-related fields to Test model

Revision ID: 2b435ba781c7
Revises: b367cbc49fdf
Create Date: 2025-12-15 16:38:50.046007

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2b435ba781c7'
down_revision = 'b367cbc49fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('show_feedback_on_completion', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('test', sa.Column('show_feedback_immediately', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'show_feedback_immediately')
    op.drop_column('test', 'show_feedback_on_completion')
    # ### end Alembic commands ###
