"""apply database schema updates

Revision ID: 2ef92487b84e
Revises: 4f2c8a6d9b11
Create Date: 2026-04-16 15:53:01.248536

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ef92487b84e'
down_revision = '4f2c8a6d9b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_test', 'question_set_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_index(op.f('ix_question_set_test_id'), table_name='question_set')
    op.drop_index(op.f('ix_test_question_question_set_id'), table_name='test_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_test_question_question_set_id'), 'test_question', ['question_set_id'], unique=False)
    op.create_index(op.f('ix_question_set_test_id'), 'question_set', ['test_id'], unique=False)
    op.alter_column('candidate_test', 'question_set_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###
