"""Add permissions for entity

Revision ID: 303084e65c1e
Revises: a5c2082ddd43
Create Date: 2026-02-03 15:05:30.987697

"""
from alembic import op
from app.models.permission import Permission
from app.models.role import Role, RolePermission
import sqlalchemy as sa
from sqlmodel import Session, select
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '303084e65c1e'
down_revision = 'a5c2082ddd43'
branch_labels = None
depends_on = None



def upgrade():


    # Add certificate permissions
    bind = op.get_bind()
    session = Session(bind=bind)

    entity_permissions = [
        {
            "name": "create_entity",
            "description": "Create New Entity",
            "roles": ["super_admin", "system_admin"],
        },
        {
            "name": "update_entity",
            "description": "Update Existing Entity",
            "roles": ["super_admin", "system_admin"],
        },
        {
            "name": "delete_entity",
            "description": "Delete Existing Entity",
            "roles": ["super_admin", "system_admin"],
        },
        {
            "name": "read_entity",
            "description": "Read Entity Details",
            "roles": ["super_admin", "system_admin", "state_admin", "test_admin"],
        },
    ]

    # Insert permissions and role_permissions if they do not exist
    for perm_data in entity_permissions:
        # Check if permission already exists
        existing_perm = session.exec(
            select(Permission).where(Permission.name == perm_data["name"])
        ).first()

        if not existing_perm:
            # Create new permission
            new_permission = Permission(
                name=perm_data["name"],
                description=perm_data["description"],
                is_active=True,
            )
            session.add(new_permission)
            session.commit()
            session.refresh(new_permission)
            permission_id = new_permission.id
        else:
            permission_id = existing_perm.id

        # Assign permission to specified roles
        for role_name in perm_data["roles"]:
            # Get role
            role = session.exec(select(Role).where(Role.name == role_name)).first()

            if role:
                # Check if role_permission already exists
                existing_role_perm = session.exec(
                    select(RolePermission).where(
                        RolePermission.role_id == role.id,
                        RolePermission.permission_id == permission_id,
                    )
                ).first()

                if not existing_role_perm:
                    # Create role_permission
                    role_permission = RolePermission(
                        role_id=role.id, permission_id=permission_id
                    )
                    session.add(role_permission)
                    session.commit()

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove certificate permissions first
    bind = op.get_bind()
    session = Session(bind=bind)

    entity_permission_names = [
        "create_entity",
        "update_entity",
        "delete_entity",
        "read_entity",
    ]

    for perm_name in entity_permission_names:
        # Find the permission
        permission = session.exec(
            select(Permission).where(Permission.name == perm_name)
        ).first()

        if permission:
            # Remove from role_permission first (foreign key constraint)
            role_permissions = session.exec(
                select(RolePermission).where(
                    RolePermission.permission_id == permission.id
                )
            ).all()

            for role_perm in role_permissions:
                session.delete(role_perm)

            # Remove the permission
            session.delete(permission)
            session.commit()

    session.commit()

    # ### end Alembic commands ###
