"""add certificate_data to candidatetest

Revision ID: 36fb8ed74f93
Revises: bc4b80a867c5
Create Date: 2026-01-25 19:29:55.962261

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36fb8ed74f93'
down_revision = 'bc4b80a867c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_test', sa.Column('certificate_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_test', 'certificate_data')
    # ### end Alembic commands ###
