"""Created alembic migration for index modification

Revision ID: 4295f412e7f9
Revises: 594fa4e77a5d
Create Date: 2026-03-11 10:54:36.966460

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4295f412e7f9'
down_revision = '594fa4e77a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entitytype_name'), table_name='entity_type')
    op.create_index(op.f('ix_entity_type_name'), 'entity_type', ['name'], unique=False)
    op.drop_index(op.f('ix_tagtype_name'), table_name='tag_type')
    op.create_index(op.f('ix_tag_type_name'), 'tag_type', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_type_name'), table_name='tag_type')
    op.create_index(op.f('ix_tagtype_name'), 'tag_type', ['name'], unique=False)
    op.drop_index(op.f('ix_entity_type_name'), table_name='entity_type')
    op.create_index(op.f('ix_entitytype_name'), 'entity_type', ['name'], unique=False)
    # ### end Alembic commands ###
