"""Remove links from test table

Revision ID: 44b95b87d350
Revises: 5b4a66539713
Create Date: 2026-04-22 08:58:13.121761

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44b95b87d350'
down_revision = '5b4a66539713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
