"""Add locale field to Test model

Revision ID: 61e8fcf99159
Revises: b367cbc49fdf
Create Date: 2025-12-08 13:07:16.329933

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '61e8fcf99159'
down_revision = 'b367cbc49fdf'
branch_labels = None
depends_on = None

locale_enum = sa.Enum('EN_US', 'HI_IN', name='localeenum')
def upgrade():
    locale_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('locale', sa.Enum('EN_US', 'HI_IN', name='localeenum'), server_default='EN_US', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'locale')
    locale_enum.drop(op.get_bind())
    # ### end Alembic commands ###
