"""add matrix-string and matrix-number question types

Revision ID: 651a91a04a29
Revises: db0cc58b6583
Create Date: 2026-03-24 16:59:27.312015

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '651a91a04a29'
down_revision = 'db0cc58b6583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE questiontype ADD VALUE IF NOT EXISTS 'matrix_input'")

    # ### end Alembic commands ###


def downgrade():
    # PostgreSQL does not support removing values from an existing enum type.
    pass
