"""Add numerical-decimal question type

Revision ID: 69cec3bb0d87
Revises: 61e8fcf99159
Create Date: 2026-01-06 12:58:35.468274

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '69cec3bb0d87'
down_revision = '61e8fcf99159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE questiontype ADD VALUE IF NOT EXISTS 'numerical_decimal'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
