"""rename table names

Revision ID: 6d50cfd8d0a9
Revises: 74063156ae27
Create Date: 2026-02-24 13:59:31.080298

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d50cfd8d0a9'
down_revision = '74063156ae27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('entitytype', 'entity_type')
    op.rename_table('tagtype', 'tag_type')
    op.rename_table('userstate', 'user_state')
    op.rename_table('userdistrict', 'user_district')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('entity_type', 'entitytype')
    op.rename_table('tag_type', 'tagtype')
    op.rename_table('user_state', 'userstate')
    op.rename_table('user_district', 'userdistrict')
    # ### end Alembic commands ###
