"""allow null response in candidate_test_answer

Revision ID: 705a8c3d0b59
Revises: 176a93f83db9
Create Date: 2026-01-13 04:02:17.733149

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '705a8c3d0b59'
down_revision = '176a93f83db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_test_answer', 'response',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_test_answer', 'response',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
