"""add tag_random JSON field to tests table

Revision ID: 745b2b45149a
Revises: db0ce83e0de2
Create Date: 2025-09-01 12:16:58.383726

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '745b2b45149a'
down_revision = 'db0ce83e0de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('tag_random', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'tag_random')
    # ### end Alembic commands ###
