"""Add post-submission review toggle (is_review_enabled) to Test

Revision ID: 7682d4a9962e
Revises: b367cbc49fdf
Create Date: 2025-11-27 17:20:27.631426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7682d4a9962e'
down_revision = 'b367cbc49fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('is_review_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'is_review_enabled')
    # ### end Alembic commands ###
