"""added question type matrix rating

Revision ID: 7d90fad13571
Revises: dd491959bf1f
Create Date: 2026-03-16 10:48:34.262779

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7d90fad13571'
down_revision = 'dd491959bf1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE questiontype ADD VALUE IF NOT EXISTS 'matrix_rating'")
    # ### end Alembic commands ###


def downgrade():
    # PostgreSQL does not support removing values from an existing enum type.
    pass
