"""Add omr Field to Test Model

Revision ID: 863d856fdcee
Revises: 61e8fcf99159
Create Date: 2026-01-08 12:42:56.212376

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '863d856fdcee'
down_revision = '61e8fcf99159'
branch_labels = None
depends_on = None

omrmode = sa.Enum('NEVER', 'ALWAYS', 'OPTIONAL', name='omrmode')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    omrmode.create(op.get_bind())
    op.add_column('test', sa.Column('omr', sa.Enum('NEVER', 'ALWAYS', 'OPTIONAL', name='omrmode'), server_default='NEVER', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'omr')
    # ### end Alembic commands ###
