"""add organization_id to role

Revision ID: 896357489d28
Revises: d8640b20c143
Create Date: 2026-08-14 13:10:28.104830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896357489d28'
down_revision = 'd8640b20c143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('role_organization_id_name_key', 'role', ['organization_id', 'name'])
    op.create_foreign_key('role_organization_id_fkey', 'role', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_organization_id_fkey', 'role', type_='foreignkey')
    op.drop_constraint('role_organization_id_name_key', 'role', type_='unique')
    op.drop_column('role', 'organization_id')
    # ### end Alembic commands ###
