"""add current_question_revision_id to candidate_test

Revision ID: 929353af67bf
Revises: fe6a2f1b6886
Create Date: 2026-06-24 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "929353af67bf"
down_revision = "fe6a2f1b6886"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_test",
        sa.Column("current_question_revision_id", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidate_test", "current_question_revision_id")
    # ### end Alembic commands ###
