"""Add question_id field to QuestionRevision

Revision ID: 9523d37ecf45
Revises: 4b67ce0b461a
Create Date: 2025-07-09 06:39:42.099616

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9523d37ecf45'
down_revision = '4b67ce0b461a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_test', sa.Column('question_revision_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_test', 'question_revision_ids')
    # ### end Alembic commands ###
