"""Rename tag_random to random_tag_count

Revision ID: 97f95c322107
Revises: 745b2b45149a
Create Date: 2025-09-02 11:31:59.882762

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97f95c322107'
down_revision = '745b2b45149a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('random_tag_count', sa.JSON(), nullable=True))
    op.drop_column('test', 'tag_random')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('tag_random', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('test', 'random_tag_count')
    # ### end Alembic commands ###
