"""Add new feedback-related fields to Test model

Revision ID: 9e3b06e6fc34
Revises: 61e8fcf99159
Create Date: 2025-12-23 15:58:57.265981

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9e3b06e6fc34'
down_revision = '61e8fcf99159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('show_feedback_on_completion', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('test', sa.Column('show_feedback_immediately', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'show_feedback_immediately')
    op.drop_column('test', 'show_feedback_on_completion')
    # ### end Alembic commands ###
