"""Add new feedback-related fields to Test model

Revision ID: a5c2082ddd43
Revises: e92a68d46642
Create Date: 2026-01-28 20:42:19.475176

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a5c2082ddd43'
down_revision = 'e92a68d46642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('show_feedback_on_completion', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('test', sa.Column('show_feedback_immediately', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'show_feedback_immediately')
    op.drop_column('test', 'show_feedback_on_completion')
    # ### end Alembic commands ###
