"""Add Mark For Review Field

Revision ID: a71d736b3809
Revises: 6d50cfd8d0a9
Create Date: 2026-03-09 13:46:19.918225

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a71d736b3809'
down_revision = '6d50cfd8d0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entitytype_name'), table_name='entity_type')
    op.create_index(op.f('ix_entity_type_name'), 'entity_type', ['name'], unique=False)
    op.drop_index(op.f('ix_tagtype_name'), table_name='tag_type')
    op.create_index(op.f('ix_tag_type_name'), 'tag_type', ['name'], unique=False)
    op.add_column('test', sa.Column('show_mark_for_review', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'show_mark_for_review')
    op.drop_index(op.f('ix_tag_type_name'), table_name='tag_type')
    op.create_index(op.f('ix_tagtype_name'), 'tag_type', ['name'], unique=False)
    op.drop_index(op.f('ix_entity_type_name'), table_name='entity_type')
    op.create_index(op.f('ix_entitytype_name'), 'entity_type', ['name'], unique=False)
    # ### end Alembic commands ###
