"""Initial migration

Revision ID: a86e6e857f37
Revises:
Create Date: 2025-05-27 11:18:57.685560

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a86e6e857f37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('candidate_uuid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_candidate_candidate_uuid'), 'candidate', ['candidate_uuid'], unique=True)
    op.alter_column('candidate_test', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('test', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('candidate_test', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_candidate_candidate_uuid'), table_name='candidate')
    op.drop_column('candidate', 'candidate_uuid')
    # ### end Alembic commands ###
