"""add show_question_palette field to test model

Revision ID: ae688477032d
Revises: 61e8fcf99159
Create Date: 2026-01-10 05:51:48.851410

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ae688477032d'
down_revision = '61e8fcf99159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('show_question_palette', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'show_question_palette')
    # ### end Alembic commands ###
