"""Remove is delete field

Revision ID: b367cbc49fdf
Revises: cae4d5024515
Create Date: 2025-10-15 13:17:12.261859

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b367cbc49fdf'
down_revision = 'cae4d5024515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'is_deleted')
    op.drop_column('question_revision', 'is_deleted')
    op.drop_column('tag', 'is_deleted')
    op.drop_column('tagtype', 'is_deleted')
    op.drop_column('test', 'is_deleted')
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('test', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tagtype', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tag', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('question_revision', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('question', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
