"""Added logo and shortcode fields to the organization model

Revision ID: b71c076d89a3
Revises: 705a8c3d0b59
Create Date: 2026-01-20 12:06:50.498790

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b71c076d89a3'
down_revision = '705a8c3d0b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('shortcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('organization', sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_organization_shortcode'), 'organization', ['shortcode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_shortcode'), table_name='organization')
    op.drop_column('organization', 'logo')
    op.drop_column('organization', 'shortcode')
    # ### end Alembic commands ###
