"""Add organization_id to certificate table

Revision ID: bc4b80a867c5
Revises: e618d3c00798
Create Date: 2026-01-22 15:35:19.716355

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bc4b80a867c5'
down_revision = 'e618d3c00798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'certificate', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificate', type_='foreignkey')
    op.drop_column('certificate', 'organization_id')
    # ### end Alembic commands ###
