"""add migration for review configuration setup

Revision ID: c0995f96ecf4
Revises: 4295f412e7f9
Create Date: 2026-03-11 10:56:40.907339

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c0995f96ecf4'
down_revision = '4295f412e7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('show_mark_for_review', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'show_mark_for_review')
    # ### end Alembic commands ###
