"""Add feedback_per_question  field to Test model

Revision ID: c32bdc71fd55
Revises: b367cbc49fdf
Create Date: 2025-12-04 20:56:43.328697

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c32bdc71fd55'
down_revision = 'b367cbc49fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('show_instant_feedback', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'show_instant_feedback')
    # ### end Alembic commands ###
