"""Add org_ids to candidate and tests

Revision ID: cae4d5024515
Revises: de518b7356af
Create Date: 2025-09-29 23:59:17.459845

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cae4d5024515'
down_revision = 'de518b7356af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate', 'organization', ['organization_id'], ['id'])
    op.alter_column('organization_provider', 'config_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('test', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.drop_column('test', 'organization_id')
    op.alter_column('organization_provider', 'config_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'organization_id')
    # ### end Alembic commands ###
