"""Remove is_deleted from candidate and grant delete_candidate permission to system_admin

Revision ID: cc398777935d
Revises: fe6a2f1b6886
Create Date: 2026-06-24 16:56:29.374426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cc398777935d'
down_revision = 'fe6a2f1b6886'
branch_labels = None
depends_on = None


PERMISSIONS_TO_GRANT = ["delete_candidate"]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'is_deleted')
    # ### end Alembic commands ###

    for perm_name in PERMISSIONS_TO_GRANT:
        op.execute(
            sa.text("""
                INSERT INTO role_permission (role_id, permission_id)
                SELECT r.id, p.id
                FROM role r
                CROSS JOIN permission p
                WHERE r.name = 'system_admin'
                  AND p.name = :name
                  AND NOT EXISTS (
                      SELECT 1 FROM role_permission rp
                      WHERE rp.role_id = r.id AND rp.permission_id = p.id
                  )
            """).bindparams(name=perm_name)
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###

    for perm_name in PERMISSIONS_TO_GRANT:
        op.execute(
            sa.text("""
                DELETE FROM role_permission
                WHERE role_id = (SELECT id FROM role WHERE name = 'system_admin')
                  AND permission_id = (SELECT id FROM permission WHERE name = :name)
            """).bindparams(name=perm_name)
        )
