"""add migration for review configuration setup

Revision ID: ce223bd3d892
Revises: 4295f412e7f9
Create Date: 2026-03-11 11:44:14.829839

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce223bd3d892'
down_revision = '4295f412e7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('bookmark', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'bookmark')
    # ### end Alembic commands ###
