"""Add question_ids column to candidate_test

Revision ID: d01ee24467a6
Revises: 87bd75e3d9ca
Create Date: 2025-07-07 12:16:52.263876

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd01ee24467a6'
down_revision = '87bd75e3d9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_test', sa.Column('question_ids', sa.JSON(), nullable=True))
    op.alter_column('tag', 'tag_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'tag_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('candidate_test', 'question_ids')
    # ### end Alembic commands ###
