"""add show_marks field

Revision ID: d98aa1873f6d
Revises: 2ef92487b84e
Create Date: 2026-04-16 16:03:09.029725

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd98aa1873f6d'
down_revision = '2ef92487b84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('show_marks', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'show_marks')
    # ### end Alembic commands ###
