"""Fix question_id null constraint

Revision ID: db0ce83e0de2
Revises: b0a29fe32d37
Create Date: 2025-08-20 18:09:20.879387

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'db0ce83e0de2'
down_revision = 'b0a29fe32d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_revision_question_id_fkey', 'question_revision', type_='foreignkey')
    op.create_foreign_key(None, 'question_revision', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_revision', type_='foreignkey')
    op.create_foreign_key('question_revision_question_id_fkey', 'question_revision', 'question', ['question_id'], ['id'])
    # ### end Alembic commands ###
