"""added question type matric match

Revision ID: dd491959bf1f
Revises: 594fa4e77a5d
Create Date: 2026-03-10 14:43:20.276766

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd491959bf1f'
down_revision = '594fa4e77a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE questiontype ADD VALUE IF NOT EXISTS 'matrix_match'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
