"""field question_revision_ids added in candidate_test table

Revision ID: e3f2d7a2db6f
Revises: 87bd75e3d9ca
Create Date: 2025-07-09 04:42:49.500087

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3f2d7a2db6f'
down_revision = '87bd75e3d9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_test', sa.Column('question_revision_ids', sa.JSON(), nullable=True))
    op.drop_column('candidate_test', 'question_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_test', sa.Column('question_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('candidate_test', 'question_revision_ids')
    # ### end Alembic commands ###
