"""Add marking_scheme field to Test

Revision ID: e52741f9df68
Revises: 5df93aaac93f
Create Date: 2025-07-21 07:57:20.872719

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e52741f9df68'
down_revision = '5df93aaac93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('marking_scheme', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'marking_scheme')
    # ### end Alembic commands ###
