"""Add certificate configuration

Revision ID: e618d3c00798
Revises: 705a8c3d0b59
Create Date: 2026-01-22 14:52:20.209825

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlmodel import Session, select

from app.models import Permission, Role, RolePermission

# revision identifiers, used by Alembic.
revision = 'e618d3c00798'
down_revision = 'b71c076d89a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_name'), 'certificate', ['name'], unique=False)
    op.add_column('test', sa.Column('certificate_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_test_certificate_id', 'test', 'certificate', ['certificate_id'], ['id'])
    # ### end Alembic commands ###

    # Add certificate permissions
    bind = op.get_bind()
    session = Session(bind=bind)

    certificate_permissions = [
        {
            "name": "create_certificate",
            "description": "Create New Certificate",
            "roles": ["super_admin", "system_admin"],
        },
        {
            "name": "update_certificate",
            "description": "Update Existing Certificate",
            "roles": ["super_admin", "system_admin"],
        },
        {
            "name": "delete_certificate",
            "description": "Delete Existing Certificate",
            "roles": ["super_admin", "system_admin"],
        },
        {
            "name": "read_certificate",
            "description": "Read Certificate Details",
            "roles": ["super_admin", "system_admin"],
        },
    ]

    # Insert permissions and role_permissions if they do not exist
    for perm_data in certificate_permissions:
        # Check if permission already exists
        existing_perm = session.exec(
            select(Permission).where(Permission.name == perm_data["name"])
        ).first()

        if not existing_perm:
            # Create new permission
            new_permission = Permission(
                name=perm_data["name"],
                description=perm_data["description"],
                is_active=True,
            )
            session.add(new_permission)
            session.commit()
            session.refresh(new_permission)
            permission_id = new_permission.id
        else:
            permission_id = existing_perm.id

        # Assign permission to specified roles
        for role_name in perm_data["roles"]:
            # Get role
            role = session.exec(select(Role).where(Role.name == role_name)).first()

            if role:
                # Check if role_permission already exists
                existing_role_perm = session.exec(
                    select(RolePermission).where(
                        RolePermission.role_id == role.id,
                        RolePermission.permission_id == permission_id,
                    )
                ).first()

                if not existing_role_perm:
                    # Create role_permission
                    role_permission = RolePermission(
                        role_id=role.id, permission_id=permission_id
                    )
                    session.add(role_permission)
                    session.commit()

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove certificate permissions first
    bind = op.get_bind()
    session = Session(bind=bind)

    certificate_permission_names = [
        "create_certificate",
        "update_certificate",
        "delete_certificate",
        "read_certificate",
    ]

    for perm_name in certificate_permission_names:
        # Find the permission
        permission = session.exec(
            select(Permission).where(Permission.name == perm_name)
        ).first()

        if permission:
            # Remove from role_permission first (foreign key constraint)
            role_permissions = session.exec(
                select(RolePermission).where(
                    RolePermission.permission_id == permission.id
                )
            ).all()

            for role_perm in role_permissions:
                session.delete(role_perm)

            # Remove the permission
            session.delete(permission)
            session.commit()

    session.commit()

    # Drop tables and columns
    op.drop_constraint('fk_test_certificate_id', 'test', type_='foreignkey')
    op.drop_column('test', 'certificate_id')
    op.drop_index(op.f('ix_certificate_name'), table_name='certificate')
    op.drop_table('certificate')
    # ### end Alembic commands ###
