"""Add language field to Test model

Revision ID: ebfd45b09052
Revises: b367cbc49fdf
Create Date: 2025-12-04 15:04:05.697883

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ebfd45b09052'
down_revision = 'b367cbc49fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    language_enum = sa.Enum('EN_US', 'HI_IN', 'MR_IN', name='languagelabels')
    language_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'test',
        sa.Column(
            'locale',
            sa.Enum('EN_US', 'HI_IN', 'MR_IN', name='languagelabels'),
            server_default='EN_US',
            nullable=False,
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'locale')
    sa.Enum(name='languagelabels').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
