"""is_active field is updated to bool only with default value true

Revision ID: ec341854b5e6
Revises: aa9cdb105214
Create Date: 2025-06-26 11:48:28.328893

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ec341854b5e6'
down_revision = 'aa9cdb105214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('candidate', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('country', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('district', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('organization', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('question', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('question_revision', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('state', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tag', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tagtype', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('test', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('test', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tagtype', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tag', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('state', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('question_revision', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('question', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('organization', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('district', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('country', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('candidate', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('block', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
