"""add show_marks field

Revision ID: f6b6c797b24e
Revises: 2ef92487b84e
Create Date: 2026-04-18 09:42:54.382112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f6b6c797b24e'
down_revision = '2ef92487b84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('show_marks', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'show_marks')
    # ### end Alembic commands ###
