"""added is reviewed field

Revision ID: f915b1a8ea67
Revises: 303084e65c1e
Create Date: 2026-02-06 14:09:21.406262

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f915b1a8ea67'
down_revision = '303084e65c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_test_answer', sa.Column('is_reviewed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_test_answer', 'is_reviewed')
    # ### end Alembic commands ###
