"""add random_tag_count field to test table

Revision ID: fe4b0aece325
Revises: db0ce83e0de2
Create Date: 2025-09-03 09:26:53.298744

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fe4b0aece325'
down_revision = 'db0ce83e0de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('random_tag_count', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'random_tag_count')
    # ### end Alembic commands ###
