name: Deploy to Production tag

# Trigger only when a tag matching v* is pushed (eg v1.2.3)
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout (for logs)
        uses: actions/checkout@v4

      - name: Deploy via SSH (tag-based)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          
          script: |
            cd /home/ubuntu
            cd sashakt-core-test

            set -euxo pipefail

            # The ref that triggered this workflow, e.g. refs/tags/v1.2.3
            GITHUB_REF="${GITHUB_REF:-${GITHUB_REF}}"
            echo "GITHUB_REF=${GITHUB_REF}"

            # Extract tag name from ref
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "Deploying tag: ${TAG_NAME}"

            # Ensure git repo is clean and has tags
            git fetch --prune --tags origin

            # Checkout the exact tag (force to ensure clean working tree)
            git checkout -f "tags/${TAG_NAME}"

            # If you want to set to a detached branch (optional)
            # git checkout -B "deploy-${TAG_NAME}" "tags/${TAG_NAME}"
            echo "Deployment of tag ${TAG_NAME} completed."
